require_relative "strategy" # typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sisakulint < Formula
  desc "Support tools for GitHub Actions workflow files"
  homepage "https://github.com/sisaku-security/sisakulint"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.1.7/sisakulint_0.1.7_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "42f2f11b18b7f99b4603eb5e918da54bc68ad1910ac0c58d03f7edd2ede126a3"

      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.1.7/sisakulint_0.1.7_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ddf13c3add2912e7be8a481b149b46f0d5b2c128635d2f5dafe84db07bbbef7a"

      def install
        bin.install "sisakulint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.1.7/sisakulint_0.1.7_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "962ec767d2169aefe60c683cfb591eaffcc813ff6b2cbe45fd90d760a7191d65"
      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.1.7/sisakulint_0.1.7_linux_armv6.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "02eb2e53d5023acc443893312e38bc8621aabb6ac768e449bf06eb46a144a38b"
      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.1.7/sisakulint_0.1.7_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c12f9106f7ed239823ed1efc82ed6d0ad493cdf5053c89155a9c7c0045f7cb51"
      def install
        bin.install "sisakulint"
      end
    end
  end

  test do
    system "#{bin}/sisakulint -version"
  end
end
