on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "example.com/owner/image"
      credentials:
        username: user
        # ERROR: Hardcoded password
        password: "hardcodedPassword123"
    services:
      redis:
        image: redis
        credentials:
          username: user
          # ERROR: Hardcoded password
          password: "anotherHardcodedPassword456"
    steps:
      - run: echo 'hello'
