name: Auto Label Issue
on:
  issue_comment:
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: Label issue
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          if [[ "$COMMENT_BODY" == *"bug"* ]]; then
            echo "Labeling as bug"
            # Command to label the issue as a bug
          fi

# この例では、ワークフローは新しい問題のコメントごとにトリガーされます。
# コメントの内容をチェックし、それに応じて問題にラベルを付けます。
# しかし、COMMENT_BODYが適切にサニタイズまたは検証されていない場合、攻撃者はコメントにコマンドを挿入し、
# ワークフローが実行されるときに実行される可能性があります。
# 例えば、"bug; rm -rf /"というコメントがrm -rf /の実行につながる可能性があります。
