on: push
jobs:
  foo:
    runs-on: ubuntu-latest
    # With permissions
    steps:
      - run: echo hello
  bar:
    runs-on: ubuntu-latest
    # Without permissions
    steps:
      - uses: actions/checkout@v3
