on:
  pull_request:
    types: [opened, synchronize]

jobs:
  use_pr_title:
    runs-on: ubuntu-latest
    steps:
    - name: Print PR Title
      run: echo "Pull Request Title is ${{ github.event.pull_request.title }}"
