on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
    # Checks out code from the incoming pull request
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Executes scripts or runs commands based on the checked out code
    - name: Build and deploy
      run: make deploy
