jobs:
  example-job-ng:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: npm test
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      - name: build
        run: npm build
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
  example-job-ok:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: npm test
      - name: build
        run: npm build
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
