on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: print log
        run: echo "Hello, GitHub Actions"
        timeout-minutes: 5
      - name: print log 2
        run: echo "Hello, GitHub Actions 2"
