name: depup
on:
  schedule:
    - cron: "6 7 * * *"
  repository_dispatch:
    types: [depup]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update reviewdog to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update reviewdog to ${{ steps.depup.outputs.latest }}"
          body: |
            Update reviewdog to [v${{ steps.depup.outputs.latest }}](https://github.com/reviewdog/reviewdog/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/reviewdog/reviewdog/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/reviewdog
          base: main
          labels: "bump:minor"

  sisakulint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: SISAKULINT_VERSION
          repo: ultra-supara/homebrew-sisakulint

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update sisakulint to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update sisakulint to ${{ steps.depup.outputs.latest }}"
          body: |
            Update sisakulint to [v${{ steps.depup.outputs.latest }}](https://github.com/ultra-supara/homebrew-sisakulint/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/ultra-supara/homebrew-sisakulint/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/sisakulint
          base: main
          labels: "bump:minor"
