name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  sisakulint:
    name: runner / sisakulint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sisakulint
        uses: ./
        with:
          tool_name: sisakulint

  reviewdog:
    name: runner / reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sisakulint w/ reviewdog
        uses: ./
        with:
          sisakulint_flags: script/broken.yaml
          tool_name: reviewdog
