name: Run sisakulint from GitHub Actions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 5 * * 1"


jobs:
  sisakulint-job:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install sisakulint
      run: |
        brew tap ultra-supara/homebrew-sisakulint
        brew install sisakulint

    - name: Clone oss repository
      run: git clone https://github.com/goreleaser/goreleaser.git

    - name: Run sisakulint on goreleaser
      run: |
        cd goreleaser
        sisakulint -debug
