name: Run sisakulint from GitHub Actions
on: [push]

jobs:
  sisakulint-job:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install sisakulint
      run: |
        brew tap ultra-supara/homebrew-sisakulint
        brew install sisakulint

    - name: Run sisakulint
      run: |
        sisakulint -h
        git clone https://github.com/goreleaser/goreleaser.git
        sisakulint -debug
